import Head from "next/head";
import Image from "next/image";
import Link from 'next/link';
import Navbar from "../../components/Navbar";
import Nav from "../../components/Nav";
import Footer from "../../components/Footer";
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.home}>
      <Head>
        <title>VALORANT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />  
      </Head>
      <div className={styles.container}>
          <Navbar/>
          <header className={styles.header}>
            <p>Um jogo de tiro tático 5x5 com personagens originais</p>
            <Image src="/images/logo_valorant.webp" width="380" height="76" alt="Logo do VALORANTE"/>
            <form>
              <button>JOGUE GRÁTIS</button>
            </form>
          </header>
          <main>
            <section className={styles.box2}>
              <h1>ÚLTIMAS NOTÍCIAS</h1>
              <p>IR PARA A PÁGINA DE NOTÍCIAS</p>
              <div>
                <Image src="/images/iso-valorant.webp" width="350" height="200" alt="classguide"/>
                <p>mês passado</p>
                <h3>VCT Game Changers Brazil: escalações oficiais da Etapa 2</h3>
                <p>Veja jogadores inscritas para a competição</p>
              </div>
              <div>
                <Image src="/images/agent.webp" width="350" height="200" alt="Agent"/>
                <p>semana passada</p>
                <h3>Tudo que você precisa saber: OFF//SEASON 2024</h3>
                <p>Descubra o que vem aí no VALORANT Esports imediatamente aós o Champions!</p>
              </div>
              <div>
                <Image src="/images/Viper.jpg" width="350" height="200" alt="Viper"/>
                <p><span>ATUALIZAÇÕES DO JOGO</span>semana passada</p>
                <h3>Notas da Atualização 9.03</h3>
                <p>Melhorias nas habilidades que se espalham pelo chão e chegada do Pearl aos modos Sem Classificação e Frenético nos consoles.</p>
              </div>
            </section>
            <section className={styles.box3}>
              <h2>LANÇAMENTO PARA CONSOLE</h2>
              <p>VALORANT // ANO 4</p>
              <button>JOGUE AGORA</button>
            </section>
            <section className={styles.box4}>
              <h2>NÓS SOMOS VALORANT</h2>
              <h3>DESAFIE SEUS LIMITES</h3>
              <p>Misture o seu estilo e experiência em um cenário global e competitivo. Você terá 13 rodadas para atacar e defender com disparos certeiros e habilidades táticas. Com apenas uma vida por rodada, você deve pensar mais rápido que o oponente se quiser sobreviver. Encare inimigos nos modos Competitivo e Sem Ranque, além da Disputa da Spike e do Mata-Mata!</p>
              <Image src="" alt=""/>
              <button>CONHEÇA O JOGO</button>
            </section>
            <aside>
            <div className={styles.box5}>
                  <Image src="" alt=""/>
                  <h2>SEUS AGENTES</h2>
                  <p>Mais do que armas e munição, VALORANT inclui agentes com habilidades adaptativas, rápidas e letais, que criam oportunidades para você exibir sua mecânica de tiro. Cada Agente é único, assim como os momentos de destaque de cada partida!</p>
                  <button>
                    <Link href="/agentes">VER TODOS OS AGENTES</Link>
                  </button>
            </div>
            </aside>
            <section className={styles.box6}>
              <h2>SEUS MAPAS</h2>
              <h3>BATALHE AO REDOR DO MUNDO</h3>
              <p>Cada mapa serve como um palco para mostrar sua criatividade. Os mapas são feitos sob medida para estratégias de equipe, jogadas espetaculares e momentos eletrizantes. Faça as jogadas que todo mundo vai tentar imitar no futuro!</p>
              <button>VER TODOS OS MAPAS</button>
            </section>
          </main>
          <Nav/>
          <Footer/>
      </div>


    </div>

  );
}
